sudo: false
language: go

matrix:
  include:
    - os: osx
      osx_image: xcode8.1 # macOS 10.12
    - os: osx
      osx_image: xcode7.3 # macOS 10.11
    - os: osx
      osx_image: xcode6.4 # macOS 10.10
  fast_finish: true

before_script:
  - sw_vers
  - go get -u github.com/golang/lint/golint

script:
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic

after_script:
  - test -z "$(gofmt -s -l -w . | tee /dev/stderr)"
  - test -z "$(golint ./...     | tee /dev/stderr)"
  - go vet ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
